crm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    
]

home/urls.py
from django.urls import path
from  home import views

urlpatterns = [
    path('',views.index,name='index'),
    path('student/',views.student,name='student'),
    path('signin/',views.signin,name="signin"),
    path('signup/',views.signup,name="signup"),
    path('book_library/',views.book_library,name="book_library"),
    path('show/',views.show,name="show"),
    path('edit/<int:id>',views.edit,name="edit"),
    path('update/<int:id>',views.update,name="update"),
    path('delete/<int:id>',views.delete,name="delete"),
]

home/models.py
from django.db import models

# Create your models here.
    
class Book(models.Model):
    bid = models.CharField(max_length=20)
    bname = models.CharField(max_length=20)
    aname = models.CharField(max_length=20)
    categ = models.CharField(max_length=20)
    class Meta:
        db_table = "book"
    

home/forms.py
from django import forms
from home.models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

home/views.py
from django.shortcuts import render,redirect
from home.forms import BookForm
from home.models import Book
from django.http import HttpResponse
import mysql.connector as sql
fn =''
ln =''
em =''
pwd =''


# Create your views here.

def index(request):
    return render(request,'index.html')

def student(request):
    books = Book.objects.all()
    return render(request,"student.html", {'books':books})
    # return render(request,'student.html')

def signin(request):
    global em,pwd
    if request.method == "POST":
        m=sql.connect(host="localhost",user="root",passwd="manojzine8@1435",database='website')
        cursor=m.cursor()
        d=request.POST
        for key,value in d.items():
            if key=="email":
                em=value  
            if key=="password":
                pwd=value    

        c="select * from users where email='{}' and password='{}'".format(em,pwd)
        cursor.execute(c)
        t=tuple(cursor.fetchall())
        if t==():
            return render(request,'signin.html')
        else:
            # return render(request,"show.html")
             return redirect("/show")

    return render(request,'signin.html')

def signup(request):
    global fn,ln,em,pwd
    if request.method == "POST":
        m=sql.connect(host="localhost",user="root",passwd="manojzine8@1435",database='website')
        cursor=m.cursor()
        d=request.POST
        for key,value in d.items():
            if key=="first_name":
                fn=value
            if key=="last_name":
                ln=value  
            if key=="email":
                em=value  
            if key=="password":
                pwd=value    

        c="insert into users values('{}','{}','{}','{}')".format(fn,ln,em,pwd)
        cursor.execute(c)
        m.commit()
        return redirect('/signin')

    return render(request,'signup.html')


def book_library(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
                # return render(request,'show.html')
            except:
                pass
    else:
        form=BookForm()                
    return render(request,'book_library.html',{'form':form})


def show(request):
    books = Book.objects.all()
    return render(request,"show.html", {'books':books})

def edit(request, id):
    book = Book.objects.get(id=id)
    return render(request,"edit.html",{'book':book})

def update(request, id):
    book= Book.objects.get(id=id)
    form = BookForm(request.POST, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request,"edit.html",{'book':book})

def delete(request,id):
    book = Book.objects.get(id=id)
    book.delete()
    return redirect("/show")

    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" type="text/css">
</head>

<body>

    {% include "header.html" %}

    {% block content %}

    {% endblock content %}

    {% include "footer.html" %}

</body>

</html>

templates/book_library.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<center>
    <h3 style="margin: 24px 0px;">Add New Book Library </h3>
</center>

<section>

    <form action=" {% url 'book_library' %} " method="POST" class="post-form">
        {% csrf_token %}
        <div class="container">
            <br>
            <!-- <div class="form-group row">
                <label for="" class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                </div>
            </div> -->
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Id:</label>
                <div class="col-sm-4">
                    {{form.bid}}
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Name:</label>
                <div class="col-sm-4">
                    {{form.bname}}
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Author:</label>
                <div class="col-sm-4">
                    {{form.aname}}
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Category:</label>
                <div class="col-sm-4">
                    {{form.categ}}
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">submit</button>
                </div>
            </div>
        </div>
    </form>

</section>

{% endblock content %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<h3>Library Maanagement System</h3>

<section>

    <form action="/update/{{book.id}}" method="POST" class="post-form">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label for="" class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Edit details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Id:</label>
                <div class="col-sm-4">
                    <input type="text" name="bid" id="id_bid" required maxlength="20" value="{{book.bid}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Name:</label>
                <div class="col-sm-4">
                    <input type="text" name="bname" id="id_bname" required maxlength="20" value="{{book.bname}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Author:</label>
                <div class="col-sm-4">
                    <input type="text" name="aname" id="id_aname" required maxlength="20" value="{{book.aname}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-2 col-form-label">Book Category:</label>
                <div class="col-sm-4">
                    <input type="text" name="categ" id="id_categ" required maxlength="20" value="{{book.categ}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="" class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </div>
    </form>

</section>

{% endblock content %}

templates/footer.html
<footer>

</footer>

</body>

</html>

templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href=" {% static 'styles.css' %}">
    <title>Library management</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Library Maanagment</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signin' %}">Admin </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student' %}">Student</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<img src="{% static 'images/Library.jpg' %}" alt="" height="500px" width="100%">
<div class="heading">
  <center>
    <h3>Library Management System</h3>
  </center>
</div>


<section>
  <div class="container">
    <div class="row">
      <div class="col col-lg-6 adminp">
        <img src="{% static 'images/admin.png' %}" alt="" height="200px" width="50%"> <br>
        <div class="loglib">
          <a href="{% url 'signin' %}" class="btn btn-primary">Admin Panel</a>
        </div>
      </div>

      <div class="col col-lg-6">
        <img src="{% static 'images/students.jpg' %}" alt="" height="200px" width="50%"> <br>
        <div class="loglib">
          <a href="{% url 'student' %} " class="btn btn-primary">Student Panel</a>
        </div>

      </div>
    </div>

  </div>
</section>

{% endblock content %}

templates/show.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section>

    <table class="table table-striped table-bordered table-sm table-responsive">
        <thead class="thead-dark">
            <tr>
                <th>Book Id</th>
                <th>Book Name</th>
                <th>Book Author</th>
                <th>Category</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{book.bid}}</td>
                <td>{{book.bname}}</td>
                <td>{{book.aname}}</td>
                <td>{{book.categ}}</td>
                <td>
                    <a href="/edit/{{book.id}}"><span
                            class=" btn btn-success glyphicon glyphicon-pencil">Edit</span></a>
                    <!-- <div class="delete"><a href="/delete/{{book.id}}">Delete</a></div> -->
                    <a href="/delete/{{book.id}}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <br>
    <center><a href=" {% url 'book_library' %} " class="btn btn-primary">Add New Books</a></center>
</section>

{% endblock content %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<form action="" method="post" class="login">
    {% csrf_token %}
    <div class="imgcontainer">
        <h3>Login Form</h3>
        <!-- <img src="img_avatar2.png" alt="Avatar" class="avatar"> -->
    </div>

    <div class="container logform">
        <div class="inner">

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" required>

            <label for="password"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="password" required>


            <button type="submit">Login</button>
        </div>
    </div>
    <!-- 
    <div class="container" style="background-color:#f1f1f1">
        <button type="button" class="cancelbtn">Cancel</button>

    </div> -->
</form>
<label>
    <span class="psw">New User <a href="{% url 'signup' %}">Click here to create acount </a></span>
</label>

{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form method="post" style="border:1px solid #ccc">
    {% csrf_token %}
    <div class="container">
        <h1>Sign Up</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>
        <div class="logform inner ">
            <label for="first_name"><b>First Name</b></label>
            <input type="text" placeholder="Enter first name" name="first_name" required>

            <label for="last_name"><b>Last Name</b></label>
            <input type="text" placeholder="Enter last name" name="last_name" required>

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" required>

            <label for="password"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="password" required>



            <div class="clearfix">

                <button type="submit" class="signupbtn">Sign Up</button>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

templates/student.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section>
    <div class="container">
        <div class="studbook">
            <h3>Books For Students</h3>
        </div>
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>Book Id</th>
                    <th>Book Name</th>
                    <th>Book Author</th>
                    <th>Category</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                <tr>
                    <td>{{book.bid}}</td>
                    <td>{{book.bname}}</td>
                    <td>{{book.aname}}</td>
                    <td>{{book.categ}}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <br>
    </div>
</section>

{% endblock content %}

templates/welcome.html
{% include 'base.html' %}
{% load static %}

{% block content %}
<h3>welcome</h3>
{% endblock %}